### ISSUE TITLE
Unable to build typescript at rev e5cd686defb1a4cbdb36bd012357ba5bed28f371

### ISSUE THREAD

**Issue by dimensi** [jakebailey/every-ts#68]
Tried to build 4.9.3 version, I already have fnm installed on my computer.  Version 5.0+ builds fine
I have m1 pro 32gb, nodejs v20.12.2

```bash
Bisecting: a merge base must be tested
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 74 (delta 10), reused 8 (delta 8), pack-reused 53
Receiving objects: 100% (74/74), 7.99 MiB | 1.72 MiB/s, done.
Resolving deltas: 100% (23/23), done.
[e5cd686defb1a4cbdb36bd012357ba5bed28f371] Update package-lock.json
Building TypeScript...
Error: Command failed with exit code 1: /Users/n.nafranets/Library/Application Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/.data/fnm/fnm install 8
error: Can't download the requested binary: v8.17.0 for arm64 not found upstream.
You can `fnm ls-remote` to see available versions or try a different `--arch`.
Installing Node v8.17.0 (arm64)
    at makeError (file:///Users/n.nafranets/Library/Application%20Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///Users/n.nafranets/Library/Application%20Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runInNode (file:///Users/n.nafranets/Library/Application%20Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/dist/fnm.js:60:9)
    at async buildFuncs (file:///Users/n.nafranets/Library/Application%20Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/dist/repo.js:106:9)
    at async tryBuildFns (file:///Users/n.nafranets/Library/Application%20Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/dist/repo.js:125:13)
    at async ensureBuiltWorker (file:///Users/n.nafranets/Library/Application%20Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/dist/repo.js:159:9)
    at async ensureBuilt (file:///Users/n.nafranets/Library/Application%20Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/dist/repo.js:173:26)
    at async Bisect.executeOrThrow (file:///Users/n.nafranets/Library/Application%20Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/dist/git.js:63:9)
    at async Bisect.execute (file:///Users/n.nafranets/Library/Application%20Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/dist/common.js:50:20) {
  shortMessage: 'Command failed with exit code 1: /Users/n.nafranets/Library/Application Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/.data/fnm/fnm install 8',
  command: '/Users/n.nafranets/Library/Application Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/.data/fnm/fnm install 8',
  escapedCommand: '"/Users/n.nafranets/Library/Application Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/.data/fnm/fnm" install 8',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'Installing Node v8.17.0 (arm64)',
  stderr: "error: Can't download the requested binary: v8.17.0 for arm64 not found upstream.\n" +
    'You can `fnm ls-remote` to see available versions or try a different `--arch`.',
  cwd: '/Users/n.nafranets/project',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Unable to build typescript at rev e5cd686defb1a4cbdb36bd012357ba5bed28f371; please file a bug!
```

**Comment by jakebailey** [comment]
Ah, you're on an M1 mac, so there's no such thing as a Node 8 binary. Unfortunately I'm not sure if I can fix this; older versions of TS just need an older version of Node.

Potentially, I can force download an AMD64 build and run it in rosetta...

**Comment by dimensi** [comment]
Hi, want to build at least somehow, how to specify in fnm the possibility to build under amd. 
Really, I was surprised that typescript was built by 8 node in version 4.9.4

**Comment by jakebailey** [comment]
Hm, it shouldn't have needed that old version to build 4.9, no...

**Comment by dimensi** [comment]
I'll try to debug this to see why it's such a weird setup.

**Comment by dimensi** [comment]
Hi, I've been messing around a bit, it seems that when building a version lower than version 5 they changed the file system path handling. I'm actually crashing on this error:


<img width="1511" alt="image" src="https://github.com/jakebailey/every-ts/assets/11390039/765f1e03-7bd7-4ee8-a9fd-ed7c58255892">

```bash
'/Users/n.nafranets/Library/Application Support/fnm/node-versions/v20.12.2/installation/lib/node_modules/every-ts/.data/TypeScript'
```

It's like the space in the folder breaks everything, but if you select version 5+, there's no problem with it.


UPDATE:

Installed the package locally, no spaces in the path now, project builds fine.
```
/Users/n.nafranets/test-every-ts/node_modules/.bin/every-ts switch v4.9.5
```
