### ISSUE TITLE
Unable to build typescript at rev 9ff9c41a9a89dfeb8aed789c77aef8f329f5c0c1

### ISSUE THREAD

**Issue by ChiriVulpes** [jakebailey/every-ts#87]
<details><summary>Full log & errors</summary>

```
[9ff9c41a9a89dfeb8aed789c77aef8f329f5c0c1] Add completion test for partial generic object (#34559)
Building TypeScript...
Error: Command failed with exit code 1: C:\Users\Chiri\AppData\Roaming\nvm\v20.11.1\node_modules\every-ts\.data\fnm\fnm.exe exec --using=8 -- node_modules\.bin\gulp.cmd LKG
[13:11:45] 'buildTsc' errored after 13 s
[13:11:45] Error: Process exited with code: 2
    at ChildProcess.proc.on.exitCode (C:\Users\Chiri\AppData\Roaming\nvm\v20.11.1\node_modules\every-ts\.data\TypeScript\scripts\build\utils.js:54:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[13:11:45] 'LKG' errored after 14 s
[13:11:31] Using gulpfile ~\AppData\Roaming\nvm\v20.11.1\node_modules\every-ts\.data\TypeScript\gulpfile.js
[13:11:31] Starting 'LKG'...
[13:11:31] Starting 'generateLibs'...
[13:11:31] Starting 'buildScripts'...
[13:11:31] Finished 'generateLibs' after 121 ms
[13:11:32] Finished 'buildScripts' after 391 ms
[13:11:32] Starting 'generateDiagnostics'...
[13:11:32] Finished 'generateDiagnostics' after 713 μs
[13:11:32] Starting 'buildShims'...
[13:11:32] Starting 'buildDebugTools'...
[13:11:32] Finished 'buildShims' after 405 ms
[13:11:32] Finished 'buildDebugTools' after 406 ms
[13:11:32] Starting 'localize'...
[13:11:32] Starting 'buildTsc'...
[13:11:32] Starting 'buildServer'...
[13:11:32] Starting 'buildReleaseTsc'...
[13:11:32] Starting 'buildTypescriptServicesOut'...
[13:11:32] Starting 'buildServerLibraryOut'...
[13:11:32] Starting 'buildCancellationToken'...
[13:11:32] Starting 'buildTypingsInstaller'...
[13:11:32] Starting 'buildWatchGuard'...
[13:11:32] Starting 'generateTypesMap'...
[13:11:32] Finished 'localize' after 2.9 ms
[13:11:32] Finished 'generateTypesMap' after 3.89 ms
src/tsc/tsc.ts(2,4): error TS2339: Property 'executeCommandLine' does not exist on type 'typeof ts'.
[13:11:45] The following tasks did not complete: buildServer, <series>, <series>, <parallel>, buildReleaseTsc, buildTypescriptServicesOut, buildServerLibraryOut, buildCancellationToken, buildTypingsInstaller, buildWatchGuard
[13:11:45] Did you forget to signal async completion?
    at makeError (file:///C:/Users/Chiri/AppData/Roaming/nvm/v20.11.1/node_modules/every-ts/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///C:/Users/Chiri/AppData/Roaming/nvm/v20.11.1/node_modules/every-ts/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildFuncs (file:///C:/Users/Chiri/AppData/Roaming/nvm/v20.11.1/node_modules/every-ts/dist/repo.js:107:9)
    at async tryBuildFns (file:///C:/Users/Chiri/AppData/Roaming/nvm/v20.11.1/node_modules/every-ts/dist/repo.js:125:13)
    at async ensureBuiltWorker (file:///C:/Users/Chiri/AppData/Roaming/nvm/v20.11.1/node_modules/every-ts/dist/repo.js:159:9)
    at async ensureBuilt (file:///C:/Users/Chiri/AppData/Roaming/nvm/v20.11.1/node_modules/every-ts/dist/repo.js:173:26)
    at async Bisect.executeOrThrow (file:///C:/Users/Chiri/AppData/Roaming/nvm/v20.11.1/node_modules/every-ts/dist/git.js:63:9)
    at async Bisect.execute (file:///C:/Users/Chiri/AppData/Roaming/nvm/v20.11.1/node_modules/every-ts/dist/common.js:50:20)
    at async Bisect.validateAndExecute (C:\Users\Chiri\AppData\Roaming\nvm\v20.11.1\node_modules\every-ts\node_modules\clipanion\lib\advanced\Command.js:73:26) {
  shortMessage: 'Command failed with exit code 1: C:\\Users\\Chiri\\AppData\\Roaming\\nvm\\v20.11.1\\node_modules\\every-ts\\.data\\fnm\\fnm.exe exec --using=8 -- node_modules\\.bin\\gulp.cmd LKG',
  command: 'C:\\Users\\Chiri\\AppData\\Roaming\\nvm\\v20.11.1\\node_modules\\every-ts\\.data\\fnm\\fnm.exe exec --using=8 -- node_modules\\.bin\\gulp.cmd LKG',
  escapedCommand: '"C:\\Users\\Chiri\\AppData\\Roaming\\nvm\\v20.11.1\\node_modules\\every-ts\\.data\\fnm\\fnm.exe" exec "--using=8" -- "node_modules\\.bin\\gulp.cmd" LKG',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '[\x1B[90m13:11:31\x1B[39m] Using gulpfile ~\\AppData\\Roaming\\nvm\\v20.11.1\\node_modules\\every-ts\\.data\\TypeScript\\gulpfile.js\n' +
    "[\x1B[90m13:11:31\x1B[39m] Starting 'LKG'...\n" +
    "[\x1B[90m13:11:31\x1B[39m] Starting 'generateLibs'...\n" +
    "[\x1B[90m13:11:31\x1B[39m] Starting 'buildScripts'...\n" +
    "[\x1B[90m13:11:31\x1B[39m] Finished 'generateLibs' after 121 ms\n" +
    "[\x1B[90m13:11:32\x1B[39m] Finished 'buildScripts' after 391 ms\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'generateDiagnostics'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Finished 'generateDiagnostics' after 713 μs\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'buildShims'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'buildDebugTools'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Finished 'buildShims' after 405 ms\n" +
    "[\x1B[90m13:11:32\x1B[39m] Finished 'buildDebugTools' after 406 ms\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'localize'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'buildTsc'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'buildServer'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'buildReleaseTsc'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'buildTypescriptServicesOut'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'buildServerLibraryOut'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'buildCancellationToken'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'buildTypingsInstaller'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'buildWatchGuard'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Starting 'generateTypesMap'...\n" +
    "[\x1B[90m13:11:32\x1B[39m] Finished 'localize' after 2.9 ms\n" +
    "[\x1B[90m13:11:32\x1B[39m] Finished 'generateTypesMap' after 3.89 ms\n" +
    "src/tsc/tsc.ts(2,4): error TS2339: Property 'executeCommandLine' does not exist on type 'typeof ts'.\r\n" +
    '[\x1B[90m13:11:45\x1B[39m] The following tasks did not complete: buildServer, <series>, <series>, <parallel>, buildReleaseTsc, buildTypescriptServicesOut, buildServerLibraryOut, buildCancellationToken, buildTypingsInstaller, buildWatchGuard\n' +
    '[\x1B[90m13:11:45\x1B[39m] Did you forget to signal async completion?',
  stderr: "[\x1B[90m13:11:45\x1B[39m] 'buildTsc' errored after 13 s\n" +
    '[\x1B[90m13:11:45\x1B[39m] Error: Process exited with code: 2\n' +
    '    at ChildProcess.proc.on.exitCode (C:\\Users\\Chiri\\AppData\\Roaming\\nvm\\v20.11.1\\node_modules\\every-ts\\.data\\TypeScript\\scripts\\build\\utils.js:54:28)\n' +
    '    at emitTwo (events.js:126:13)\n' +
    '    at ChildProcess.emit (events.js:214:7)\n' +
    '    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)\n' +
    "[\x1B[90m13:11:45\x1B[39m] 'LKG' errored after 14 s",
  cwd: 'C:\\Users\\Chiri\\AppData\\Roaming\\nvm\\v20.11.1\\node_modules\\every-ts\\.data\\TypeScript',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

</details>

Is there a way to, during a bisect, retry building? Or maybe just skip this specific commit and go down or up one? Didn't see anything like that in the readme

**Comment by jakebailey** [comment]
You can do:

```
every-ts bisect skip 9ff9c41a9a89dfeb8aed789c77aef8f329f5c0c1
```
